### PR TITLE
Remove tinyproxy.log from repo

### PR DESCRIPTION
**Pull request by srl295**
Fixes: #35

### CODE REVIEW

**Comment by qbit** [comment]
Thanks!

**Comment by srl295** [comment]
@qbit now you can drop 2/3rds from the npm payload size!

**Comment by qbit** [comment]
aye, just as soon as I figure out how to publish it :P

**Comment by srl295** [comment]
@qbit set a tiny thanks as @codehivetx

**Comment by qbit** [comment]
published!

**Comment by srl295** [comment]
my app went from 460k to 244k on disk! woo

**Pull request merged**
