### PR TITLE
Feature/use request lib

### PR DESCRIPTION
**Pull request by franckOL**
Try to upgrade lib so proxy works now: ==> see issue #17

### CODE REVIEW

**Comment by qbit** [comment]
Appreciate the PR! I plan on keeping this lib external dependency free.

That said - I added some code to make http proxyies work. Check out `test/test_proxy.js` for an example.

**Comment by franckOL** [comment]
I understand for the external dependancy. But what i try also to fix is that you can set proxy externally so a lib that use node-pushover works behind proxy. I encounter the case in fact with node-red-node-pushover.

**Comment by qbit** [comment]
How is my update any different from what `request` is doing? Is `node-red-node-pushover` not able to set `httpOptions.proxy`? It seems `request` requires the same (clip from their README):

```
var r = request.defaults({'proxy':'http://localproxy.com'})
```

**Comment by franckOL** [comment]
`request` also use `process.env.HTTP_PROXY` to set proxy. 
`node-red-node-pushover` can't set  any `httpOptions` for the moment.

**Pull request closed without merging**
